security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
 
    providers:
        fos_userbundle:
                id: fos_user.user_manager
 
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:      "/oauth/check-facebook"
                    linkedin:      "/oauth/check-linkedin"
                    twitter:       "/oauth/check-twitter"
                login_path:        /
                failure_path:      /
 
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: lilo_user_provider
            logout:
                path: /logout
                target: /
                invalidate_session: false
            anonymous:    true
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
 
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, roles: ROLE_SUPER_ADMIN }