parameters:
    lilo_user_provider.class: Lilo\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    lilo_user_provider:
        class: "%lilo_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, linkedin: linkedin_id, twitter: twitter_id}]